### ISSUE TITLE
CODE lässt sich über den Eclipse Marketplace nicht installieren

### ISSUE THREAD

**Issue by flaechsig** [bastie/CODE#1]
Beim Versuch das Paket zu installieren kommt der Hinweis, dass unter der Update-Site nichts ist.

Eclipse-Version: Version: 2018-09 (4.9.0)

**Comment by bastie** [comment]
URL fehlerhaft:
false https://github.com/bastie/CODE/tree/master/UpdateSite
right https://github.com/bastie/CODE/tree/master/CODE%20UpdateSite

**Comment by Bortechino** [comment]
Eclipse Marketplace error:

> "Unable to read repository at https://github.com/bastie/CODE/tree/master/CODE%20UpdateSite.
> https://github.com/bastie/CODE/tree/master/CODE%20UpdateSite is not a valid repository location."
Eclipse Version: 2018-12 (4.10.0)
Build id: 20181214-0600

**Comment by NordicTux** [comment]
Die URL sieht sauber aus (https://github.com/bastie/CODE/tree/master/CODE%20UpdateSite), Installation ist dennoch nicht möglich. Meldung lautet "No software site found at https://..."

**Comment by GitMensch** [comment]
@bastie Sollte es nicht funktionieren wenn du eine [github-page registrierst][0] und das damit veröffentlichst?

Die neue URL wäre dann wohl etwas wie https://bastie.github.io/CODE/CODE%20UpdateSite

[0]:https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site

**Comment by froemken** [comment]
Ich habe diesen Pfad aus dem Screenshot verwendet (inkl. raw, nicht tree). Das hat funktioniert:

`https://github.com/bastie/CODE/raw/master/CODE` UpdateSite

**Comment by bastie** [comment]
Eclipse Marketplace don‘t support spaces / %20 in update URL (?)!

I think next version will repair it. Now it ist a way to use URL with space, not %20 directly in eclipse.

I‘m looking forward at March4COBOL
